version: 0.0
os: linux
files:
  - source: /
    destination: /deployment
    overwrite: yes
permissions:
  - object: /deployment/scripts/
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh       
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_container.sh      
      timeout: 300
      runas: root
