version: 0.0
os: linux
files:
  - source: /
    destination: /deployment
    overwrite: yes
permissions:
  - object: /deployment/
    pattern: "*"
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStop:
    - location: stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_container.sh
      timeout: 300
      runas: root
