version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2376 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      
  pre_build:
    commands:
      - echo "Logging into Docker Hub..."
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin
      - echo "Installing Python dependencies..."
      - pip install -r simple-python-app/requirements.txt
      
  build:
    commands:
      - echo "Starting build phase..."
      - cd simple-python-app
      - echo "Building Docker Image"
      - docker build -t jhamelthorne/myapp:latest .
      - echo "Pushing Docker Image to Docker Hub"
      - docker push jhamelthorne/myapp:latest
      - cd ..
      
  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Creating deployment package for CodeDeploy..."

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - simple-python-app/**/*
  name: deployment-package-$(date +%Y-%m-%d)
